### PR TITLE
Fixed handling for commands with 3+ arguments.

### PR DESCRIPTION
**Pull request by danhunsaker**
Per Issue #19.

### CODE REVIEW

**Comment by danhunsaker** [comment]
D'oh.  I forgot that GitHub automatically creates a new Issue when you issue a pull request.

**Comment by joelcox** [comment]
Hey Dan, thanks for your pull request. This [seems to break](https://travis-ci.org/joelcox/codeigniter-redis/jobs/3894858) when you are using array arguments, but I'll take a good look later this week.

`$this->redis->hmset('key', array('key1' => 'value1', 'key2' => 'value2'))`

Happy New Year!

**Comment by danhunsaker** [comment]
Hmmm...  I see what's happening there...  I'll whip up a fix here in just a moment.

**Comment by danhunsaker** [comment]
I'm about to push the changes I promised a bit ago, but I wanted to confirm that an array argument will always be the last one passed in.  If there are any cases where an array argument is not the last one passed, the logic gets a bit more complicated.  Based on the setup of `Redis::command()`, however, I feel the solution I'm about to push is correct.

Please let me know if I am mistaken on this!

**Comment by joelcox** [comment]
Looking at the list of Redis command this is indeed the case. I plan on adding new tests for every major command and the different notations this library supports before doing another release, just to make sure we don't break stuff unexpectedly.

@tinkertim I'm not sure how this will interfere with your downstream changes, but I'll merge this for now and we'll take care of it then if it needs work.

Thanks for your contribution Dan!

**Pull request merged**
