### PR TITLE
get_instance() function assigned by reference

### PR DESCRIPTION
**Pull request by twn39**
This change is [Reviewable](https://reviewable.io/reviews/joelcox/codeigniter-redis/54)

### CODE REVIEW

**Comment by joelcox** [comment]
Hi Tang, thanks for your pull request!

In PHP 5 objects are passed by reference by default, so I don't really see why the `&` would be necessarily. Could you elaborate? Thanks!

**Comment by twn39** [comment]
Because codeigniter manual are described, and marked: very important, maybe I need to take a closer look php5 principle。

**Comment by joelcox** [comment]
You are right, this used to be important in the PHP 4 days, but doesn't really apply to PHP 5. See this [SO question](http://stackoverflow.com/questions/9331519/how-do-you-pass-objects-by-reference-in-php-5).

**Comment by danhunsaker** [comment]
CodeIgniter requires it because it's designed for the broadest compatibility with PHP versions actually in use.  PHP 4 has been replaced on all but the most forgotten or niche of systems (or those run by the least competent sysadmins, but I digress), so CI's minimum supported version is up to 5.2 (which, stupidly, is _still_ widely deployed) - which means we no longer need the `&`.  Though it can still be useful as a reminder in some places that the return value we're expecting will be by reference, that probably won't help much here.

**Pull request closed without merging**
