### PR TITLE
Implement set commands (sadd,srem,smembers,sismember,scard) 

### PR DESCRIPTION
**Pull request by ashiina**
I had a need to use some of the set-related commands in Redis for my app,
so I went ahead and implemented them.
It'd be great if you can look over it and merge it into the master if it looks good.
*I've wrote tests to go along with it too

### CODE REVIEW

**Comment by joelcox** [comment]
Heya, thanks for your pull request. I'll look into this later this week.

**Comment by ashiina** [comment]
k thanks!
I did notice that you are making a lot of changes in your develop branch;
My commit is based on the architecture of the current master,
so if my commit is inconsistent with your new architecture 
I'm more than happy to re-write a new implementation for the "set" commands :)

**Comment by joelcox** [comment]
Hey ashiina, exactly my point!

**Comment by joelcox** [comment]
Hi ashiina. After some thinking I don't feel this is the way to go for this library. I would prefer to implement a more general method for working with multidimensional data, but I don't yet know how. My aim is to not implement any specific Redis commands and have everything handled by Redis::__call().

Thanks for thinking along.

**Comment by ashiina** [comment]
Hi joel,
Understood. 

> My aim is to not implement any specific Redis commands and have everything handled by Redis::__call().
> Yes, I agree that this is a wiser path to take.

If I come up with any way I can help I might toss it at you,
but until then, I will just go back to watching this repo.

Thank you for the great work, it's a really helpful library :)

**Comment by joelcox** [comment]
Thanks again!

**Pull request closed without merging**
