### PR TITLE
Re-adding fix for issue #40 into develop branch after merge of code from issue #33

### PR DESCRIPTION
**Pull request by integrii**

### CODE REVIEW

**Comment by integrii** [comment]
It wasn't actually issue #40 - but whatever :-)  Oops.

**Comment by joelcox** [comment]
Indeeed @danhunsaker. Yet applying the previous PR broke the build https://travis-ci.org/joelcox/codeigniter-redis/jobs/10558747

**Comment by danhunsaker** [comment]
To be fair, so would this one...

**Comment by integrii** [comment]
I am going to close this one, re-fork and make another pull request to avoid any further complications

**Pull request closed without merging**
