### PR TITLE
Assigning by reference...

### PR DESCRIPTION
**Pull request by serzhenko**
... allows you to use the original CodeIgniter object rather than creating a copy of it.

http://codeigniter.com/user_guide/general/creating_libraries.html

### CODE REVIEW

**Comment by joelcox** [comment]
Hi Dmitry,

Thanks for your pull request. Objects are always passed by reference as of PHP 5. No need to prefix the assigned object with an ampersand (&) anymore!

http://php.net/manual/en/language.oop5.references.php

Joël,
Vanaf mijn iPhone

**Comment by joelcox** [comment]
Hi @serzhenko, do you still think this is a valid pull request or can I close this?

**Comment by joelcox** [comment]
Heya. I'm closing this for now since I haven't heard from you anymore. Feel free to open it again/file a new issue if you still think this is an issue.

**Comment by serzhenko** [comment]
Hello, Joël!
Excuse me — I didn't have an opportunity to respond.

The PHP manual you referenced says

> A PHP reference is an alias, which allows two different variables to write to the same value. As of PHP 5, an object variable doesn't contain the object itself as value anymore. It only contains an object identifier which allows object accessors to find the actual object. When an object is sent by argument, returned or assigned to another variable, the different variables are not aliases: they hold a copy of the identifier, which points to the same object.

And CI User Guide I referenced in pull request emphasises the usage of ampersand

> Note: You'll notice that the above get_instance() function is being passed by reference: 
> $CI =& get_instance(); 
> This is very important. Assigning by reference allows you to use the original CodeIgniter object rather than creating a copy of it.

I think it would be better to use assignment by reference.

**Comment by joelcox** [comment]
Hi serzhenko,

You're correct, but this is still documentation from CodeIgniters PHP4 era. Also see this pull request for the CI core, where remove =& from the codebase is discussed.

https://github.com/EllisLab/CodeIgniter/pull/335

**Comment by serzhenko** [comment]
Huh. Yep, you're right.

In fact I've never used PHP prior to 5, so I've been confused a little bit about all that pre-OOP stuff %)

**Comment by joelcox** [comment]
No problem! You can leave the & in there perfectly fine, but it break the unit tests for the library :)

**Pull request closed without merging**
