### PR TITLE
Changed the way the _encode_request is building the request.

### PR DESCRIPTION
**Pull request by axelay**
This change allows for arrays with mixed content to be used, eg:
$userIds = $this->redis->sort('users', array('by' => '*->time_created',
'limit', $start, $perPage));

That answers my question in the issues list :)

### CODE REVIEW

**Comment by joelcox** [comment]
Hey Axelay, thanks for reporting you AND fixing it!

However, your commit seems to be a bit misformatted (https://github.com/axelay/codeigniter-redis/commit/5f4ad8eb3a66118d91cce15b29068a13e80937f2), could you fix this so I can easily review your changes? It would also be great if you added a unit test for the things you fixed, so we're sure we won't be breaking things in the future.

Thanks!

**Comment by axelay** [comment]
Sorry about that, think my editor replaced all the line endings or something weird :)
Here is the corrected version, will write test tonight

**Comment by joelcox** [comment]
Great. Could you also merge in the latest commit on the develop branch? Travis was acting up.

**Comment by axelay** [comment]
Sorry this is the first time I really do pull request and I don't know if I buggered things up. Seems like Travis is now happy :)

**Comment by joelcox** [comment]
Great! The commit still looks a bit funky (https://github.com/joelcox/codeigniter-redis/pull/51/files vs https://github.com/joelcox/codeigniter-redis/pull/30/files, where individual lines are marked rather than whole sections). Not sure what it causing this. If you can touch it that would be great, else I'll just merge it in this weekend.

Thanks for your contribution!

**Comment by axelay** [comment]
To be fair, some of the functions were deleted and one of them has been a complete rewrite which may explain this strange look.

**Pull request merged**
